USE [master]
GO

/****** Object:  Database [laboratoria]    Script Date: 18.05.2026 16:35:27 ******/
DROP DATABASE [laboratoria]
GO

/****** Object:  Database [laboratoria]    Script Date: 18.05.2026 16:35:27 ******/
CREATE DATABASE [laboratoria]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'laboratoria', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\laboratoria.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'laboratoria_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\laboratoria_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [laboratoria].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [laboratoria] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [laboratoria] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [laboratoria] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [laboratoria] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [laboratoria] SET ARITHABORT OFF 
GO

ALTER DATABASE [laboratoria] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [laboratoria] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [laboratoria] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [laboratoria] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [laboratoria] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [laboratoria] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [laboratoria] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [laboratoria] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [laboratoria] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [laboratoria] SET  DISABLE_BROKER 
GO

ALTER DATABASE [laboratoria] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [laboratoria] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [laboratoria] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [laboratoria] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [laboratoria] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [laboratoria] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [laboratoria] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [laboratoria] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [laboratoria] SET  MULTI_USER 
GO

ALTER DATABASE [laboratoria] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [laboratoria] SET DB_CHAINING OFF 
GO

ALTER DATABASE [laboratoria] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [laboratoria] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [laboratoria] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [laboratoria] SET  READ_WRITE 
GO

