//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class audit_log
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string action { get; set; }
        public string entity_type { get; set; }
        public Nullable<int> entity_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual users users { get; set; }
    }
}
