//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class batch_raw_usage
    {
        public int id { get; set; }
        public Nullable<int> batch_id { get; set; }
        public Nullable<int> raw_batch_id { get; set; }
        public Nullable<decimal> actual_quantity { get; set; }
    
        public virtual production_batches production_batches { get; set; }
    }
}
