//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class deviations
    {
        public int id { get; set; }
        public Nullable<int> batch_id { get; set; }
        public Nullable<int> step_execution_id { get; set; }
        public string param_name { get; set; }
        public string planned_value { get; set; }
        public string actual_value { get; set; }
        public string severity { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual production_batches production_batches { get; set; }
        public virtual step_executions step_executions { get; set; }
    }
}
