//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace desktop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class laboratoriaEntities : DbContext
    {
        public laboratoriaEntities()
            : base("name=laboratoriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<audit_log> audit_log { get; set; }
        public virtual DbSet<batch_raw_usage> batch_raw_usage { get; set; }
        public virtual DbSet<deviations> deviations { get; set; }
        public virtual DbSet<lab_tests> lab_tests { get; set; }
        public virtual DbSet<production_batches> production_batches { get; set; }
        public virtual DbSet<production_orders> production_orders { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<raw_materials> raw_materials { get; set; }
        public virtual DbSet<recipe_components> recipe_components { get; set; }
        public virtual DbSet<recipes> recipes { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<step_actual_params> step_actual_params { get; set; }
        public virtual DbSet<step_executions> step_executions { get; set; }
        public virtual DbSet<step_parameters> step_parameters { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tech_maps> tech_maps { get; set; }
        public virtual DbSet<tech_steps> tech_steps { get; set; }
        public virtual DbSet<test_results> test_results { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
