//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class production_batches
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public production_batches()
        {
            this.batch_raw_usage = new HashSet<batch_raw_usage>();
            this.deviations = new HashSet<deviations>();
            this.step_executions = new HashSet<step_executions>();
        }
    
        public int id { get; set; }
        public Nullable<int> order_id { get; set; }
        public string batch_number { get; set; }
        public byte[] start_date { get; set; }
        public string status { get; set; }
        public Nullable<int> tech_map_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<batch_raw_usage> batch_raw_usage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deviations> deviations { get; set; }
        public virtual production_orders production_orders { get; set; }
        public virtual tech_maps tech_maps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<step_executions> step_executions { get; set; }
    }
}
