//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipe_components
    {
        public int id { get; set; }
        public Nullable<int> recipe_id { get; set; }
        public Nullable<int> raw_material_id { get; set; }
        public Nullable<decimal> percentage { get; set; }
        public Nullable<int> load_order { get; set; }
        public Nullable<decimal> tolerance { get; set; }
    
        public virtual raw_materials raw_materials { get; set; }
        public virtual recipes recipes { get; set; }
    }
}
