//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class step_parameters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public step_parameters()
        {
            this.step_actual_params = new HashSet<step_actual_params>();
        }
    
        public int id { get; set; }
        public Nullable<int> step_id { get; set; }
        public string param_name { get; set; }
        public Nullable<decimal> min_value { get; set; }
        public Nullable<decimal> max_value { get; set; }
        public string unit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<step_actual_params> step_actual_params { get; set; }
        public virtual tech_steps tech_steps { get; set; }
    }
}
