//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class step_actual_params
    {
        public int id { get; set; }
        public Nullable<int> execution_id { get; set; }
        public Nullable<int> param_id { get; set; }
        public Nullable<decimal> actual_value { get; set; }
        public string comment { get; set; }
    
        public virtual step_executions step_executions { get; set; }
        public virtual step_parameters step_parameters { get; set; }
    }
}
